stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: docker/Dockerfile
      buildContext: .
      tag: img_fiware-orion_v2.2.0:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      #registry: 172.30.76.49:5000
      registry: csp2-centos-1:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./orion_deployment.yaml
timeout: 60
notification: {}
