stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: img_fiware-orion_v2.2.0:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: csp2-centos-1:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
timeout: 60
notification: {}
