stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: docker/Dockerfile
      buildContext: .
      tag: fiware-orion:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.0.8.61:31484
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: Test_postman
  steps:
  - applyYamlConfig:
      path: Postman/Postman.yaml
- name: demo_test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: echo "hello world
timeout: 60
notification: {}
