FROM centos:centos7.6.1810


ENV ORION_USER orion
ENV GIT_REV_ORION 2.2.0
ENV CLEAN_DEV_TOOLS 1

WORKDIR /opt

RUN \
    adduser --comment "${ORION_USER}" ${ORION_USER} && \
    # Install dependencies
    yum -y install epel-release && \
    yum -y install \
      boost-devel \
      bzip2 \
      cmake \
      gnutls-devel \
      libgcrypt-devel \
      libcurl-devel \
      openssl-devel \
      libuuid-devel \
      make \
      nc \
      git \
      gcc-c++ \
      scons \
      tar \
      which \
      cyrus-sasl-devel && \
    # Install libmicrohttpd from source
    curl -kOL http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.48.tar.gz && \
    tar xvf libmicrohttpd-0.9.48.tar.gz && \
    cd libmicrohttpd-0.9.48 && \
    ./configure --disable-messages --disable-postprocessor --disable-dauth && \
    make && \
    make install && \
    ldconfig && \

    #Test
    cd .. && \
    #Test

    # Install mongodb driver from source
    curl -kOL https://github.com/mongodb/mongo-cxx-driver/archive/legacy-1.1.2.tar.gz && \
    tar xfz legacy-1.1.2.tar.gz && \
    cd mongo-cxx-driver-legacy-1.1.2 && \
    scons --use-sasl-client --ssl && \
    scons install --prefix=/usr/local --use-sasl-client --ssl && \

    #Test
    cd .. && \
    #Test

    # Install rapidjson from source
    curl -kOL https://github.com/miloyip/rapidjson/archive/v1.0.2.tar.gz && \
    tar xfz v1.0.2.tar.gz && \
    mv rapidjson-1.0.2/include/rapidjson/ /usr/local/include && \

    #Test

    yum install -y wget && \
    wget https://nexus.lab.fiware.org/repository/raw/public/storage/gmock-1.5.0.tar.bz2 && \
    tar xfvj gmock-1.5.0.tar.bz2 && \
    cd gmock-1.5.0 && \
    ./configure && \
    make && \
    make install && \
    cd .. && \
    #Test

    # Install orion from source
    git clone https://github.com/prabhat2410/Orion && \
    cd Orion && \

    #Test
    yum install -y python python-flask pyOpenSSL curl nc mongodb-org-shell valgrind bc && \
    mkdir ~/bin && \
    export PATH=~/bin:$PATH && \
    make install_scripts INSTALL_DIR=~ && \
    chmod +x ./scripts/testEnv.sh && \
    ./scripts/testEnv.sh && \

    make unit_test 
    #Test
